### PR TITLE
fix case of Arduino.h include

### LINKED ISSUE #29: buzz block generates code that does not compile on Linux
**Describe the bug**

Adding a buzz block creates the line `#include <arduino.h>`. 
arduino-cli cannot compile it.

see https://github.com/leaphy-robotics/leaphy-client/issues/28

the line should be `#include <Arduino.h>`

### PR DESCRIPTION
**Pull request by bastiaanb**
fixes https://github.com/leaphy-robotics/leaphy-blockly/issues/29

### CODE REVIEW

File: generators/arduino/leaphy_original.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ Blockly.Arduino['leaphy_original_analog_read'] = function (block) {
 };
 
 Blockly.Arduino['leaphy_original_buzz'] = function(block) {
-    Blockly.Arduino.addInclude('arduino', '#include <arduino.h>');
+    Blockly.Arduino.addInclude('arduino', '#include <Arduino.h>');
```
Comment (paulsiersma) [inline generators/arduino/leaphy_original.js:62]: Nice catch. Weird how that casing is ignored on all platforms but linux ¯\_(ツ)_/¯

**Review by paulsiersma — APPROVED** [review]
